name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
